/* Engaje Mídia Hub — Integradores operacionais */
(function(){
  const INTEGRATORS=[
    {id:'meta_organic',title:'Meta Orgânico',sub:'Facebook + Instagram',connectors:['facebook_organic','instagram'],platform:'organic'},
    {id:'meta_ads',title:'Meta Ads',sub:'Facebook Ads + Instagram Ads',connectors:['facebook'],platform:'meta_ads'},
    {id:'google_ads',title:'Google Ads',sub:'Google Advertising',connectors:['google_ads'],platform:'google_ads'}
  ];
  let connected=[];
  const css=`
  #integration-center{margin-bottom:16px}.ic-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:16px}.ic-title{font-size:18px;font-weight:800;color:var(--text);letter-spacing:-.025em}.ic-sub{font-size:10px;color:var(--text2);margin-top:5px;line-height:1.55}.ic-grid{display:grid;grid-template-columns:repeat(3,minmax(220px,1fr));gap:12px}.ic-card{border:1px solid var(--border);border-radius:14px;background:linear-gradient(180deg,var(--surface2),var(--surface));padding:16px}.ic-card-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.ic-name{font-size:14px;font-weight:800}.ic-type{font-size:9px;color:var(--text3);margin-top:3px}.ic-badge{font-size:8px;font-weight:800;padding:4px 8px;border-radius:999px;background:rgba(34,197,94,.1);color:#4ade80}.ic-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.ic-account-section{border-top:1px solid rgba(148,163,184,.12);margin-top:16px;padding-top:16px}.ic-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.ic-table{width:100%;border-collapse:collapse;font-size:10px}.ic-table th{font-size:8px;text-transform:uppercase;letter-spacing:.05em;color:var(--text3);font-weight:700;text-align:left;padding:9px;border-bottom:1px solid var(--border)}.ic-table td{padding:10px 9px;border-bottom:1px solid rgba(148,163,184,.075);vertical-align:middle}.ic-table select{min-width:180px}.ic-muted{font-size:9px;color:var(--text3)}.ic-provider{font-size:8px;color:#7f8ca0;text-transform:uppercase;letter-spacing:.06em;margin-top:10px}.ic-empty{padding:22px;text-align:center;color:var(--text2);font-size:10px;border:1px dashed var(--border);border-radius:10px}.ic-danger{border-color:rgba(239,68,68,.25)!important;color:#fb7185!important}@media(max-width:980px){.ic-grid{grid-template-columns:1fr}.ic-toolbar,.ic-head{align-items:flex-start;flex-direction:column}}
  `;
  function injectStyles(){if(document.getElementById('integration-center-style'))return;const s=document.createElement('style');s.id='integration-center-style';s.textContent=css;document.head.appendChild(s)}
  function wait(fn,tries=60){if(fn())return;if(tries>0)setTimeout(()=>wait(fn,tries-1),100)}
  async function edge(slug,body){const r=await fetch(SB_URL+'/functions/v1/'+slug,{method:'POST',headers:{'Content-Type':'application/json','apikey':SB_ANON,'Authorization':'Bearer '+(SESSION?.access_token||SB_ANON)},body:JSON.stringify(body||{})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||j.message||('HTTP '+r.status));return j}
  function removeLegacyDirectBlocks(){document.querySelectorAll('#module-page .section-card').forEach(el=>{const t=(el.textContent||'').toLowerCase();if(t.includes('integração direta com a meta')||t.includes('nenhuma conta meta autorizada')||t.includes('visão das contas sincronizadas')||t.includes('windsor (legado)'))el.remove();});}
  function clientOptions(selected){return `<option value="">Não vinculado</option>`+(ST.clients||[]).filter(c=>!c.is_agency).map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(selected||'')?'selected':''}>${esc(c.name)}</option>`).join('')}
  function connectorLabel(c){return c==='facebook'?'Meta Ads':c==='google_ads'?'Google Ads':c==='facebook_organic'?'Facebook orgânico':'Instagram orgânico'}
  async function loadAccounts(){try{connected=await rest('integration_accounts?provider_id=eq.windsor&select=id,connector,external_account_id,account_name,client_id,status,last_sync_at,last_error&order=connector.asc,account_name.asc')||[];}catch{connected=[]}}
  async function discoverAccounts(){try{toast('Atualizando contas dos integradores...');const d=await edge('windsor-accounts',{});toast((d.count||0)+' contas encontradas.');await loadAccounts();renderAccounts()}catch(e){toast(e.message,'error')}}
  function renderAccounts(){const root=document.getElementById('ic-accounts');if(!root)return;const rows=connected.filter(a=>['facebook','google_ads'].includes(a.connector));if(!rows.length){root.innerHTML='<div class="ic-empty">Nenhuma conta de anúncios encontrada. Conecte Meta Ads ou Google Ads e clique em “Atualizar contas”.</div>';return;}root.innerHTML=`<div style="overflow:auto"><table class="ic-table"><thead><tr><th>Integrador</th><th>Conta</th><th>Cliente</th><th>Status</th></tr></thead><tbody>${rows.map(a=>`<tr><td><b>${connectorLabel(a.connector)}</b></td><td>${esc(a.account_name||a.external_account_id)}<div class="ic-muted">${esc(a.external_account_id)}</div></td><td><select class="ctrl-sel ic-client-map" data-id="${esc(a.id)}" data-connector="${esc(a.connector)}" data-account="${esc(a.external_account_id)}">${clientOptions(a.client_id)}</select></td><td>${a.last_sync_at?'Sincronizado':'Conectado'}<div class="ic-muted">${a.last_sync_at?new Date(a.last_sync_at).toLocaleString('pt-BR'):a.last_error?esc(a.last_error):'Aguardando sync'}</div></td></tr>`).join('')}</tbody></table></div>`;root.querySelectorAll('.ic-client-map').forEach(s=>s.onchange=()=>mapAccount(s));}
  async function mapAccount(s){try{const clientId=s.value||null;await rest('integration_accounts?id=eq.'+encodeURIComponent(s.dataset.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({client_id:clientId,updated_at:new Date().toISOString()})});await rest(`paid_media_metrics?provider_id=eq.windsor&connector=eq.${encodeURIComponent(s.dataset.connector)}&account_id=eq.${encodeURIComponent(s.dataset.account)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({client_id:clientId})});toast(clientId?'Conta vinculada ao cliente.':'Vínculo removido.');await loadAccounts();renderAccounts()}catch(e){toast(e.message,'error')}}
  async function connect(connector){try{const d=await edge('windsor-connect',{connector});if(!d.connect_url)throw new Error('URL de conexão não recebida');window.open(d.connect_url,'_blank','noopener,noreferrer')}catch(e){toast('Falha ao abrir integração: '+e.message,'error')}}
  async function syncOrganic(){try{toast('Reimportando Facebook e Instagram...');const d=await edge('windsor-sync',{days:365});toast(`Orgânico: ${d.posts||0} conteúdos e ${d.metrics||0} métricas.`);return d}catch(e){toast('Orgânico: '+e.message,'error');throw e}}
  async function syncPaid(connector){try{toast('Sincronizando '+connectorLabel(connector)+'...');const d=await edge('windsor-paid-sync',{days:365,connector});toast(`${connectorLabel(connector)}: ${d.upserted||0} registros.`);await discoverAccounts();return d}catch(e){toast(connectorLabel(connector)+': '+e.message,'error');throw e}}
  async function reimportAll(){const btn=document.getElementById('ic-reimport');if(btn){btn.disabled=true;btn.textContent='Reimportando...'}try{await discoverAccounts();await syncOrganic().catch(()=>null);await syncPaid('facebook').catch(()=>null);await syncPaid('google_ads').catch(()=>null);toast('Reimportação concluída. Revise contas não vinculadas a clientes.');if(typeof renderDashboard==='function')await renderDashboard()}finally{if(btn){btn.disabled=false;btn.textContent='Reimportar tudo'}}}
  function card(i){const buttons=i.id==='meta_organic'?`<button class="btn-sm-ghost" data-connect="facebook_organic">Conectar Facebook</button><button class="btn-sm-ghost" data-connect="instagram">Conectar Instagram</button><button class="btn-sm-prim" data-sync="organic">Sincronizar</button>`:`<button class="btn-sm-ghost" data-connect="${i.connectors[0]}">Conectar conta</button><button class="btn-sm-prim" data-sync="${i.connectors[0]}">Sincronizar</button>`;return `<div class="ic-card"><div class="ic-card-top"><div><div class="ic-name">${i.title}</div><div class="ic-type">${i.sub}</div></div><span class="ic-badge">Integrador ativo</span></div><div class="ic-provider">Coleta gerenciada pelo Windsor.ai</div><div class="ic-actions">${buttons}</div></div>`}
  async function renderIntegrationCenter(){if(typeof isSuperAdmin==='function'&&!isSuperAdmin())return;const host=document.getElementById('module-page');if(!host)return;removeLegacyDirectBlocks();document.getElementById('integration-center')?.remove();injectStyles();await loadAccounts();const box=document.createElement('section');box.id='integration-center';box.className='section-card';box.innerHTML=`<div class="ic-head"><div><div class="ic-title">Integradores</div><div class="ic-sub">Somente integrações que vamos usar. Sem conexão direta duplicada e sem seletor de provedores.</div></div><div class="ic-actions"><button class="btn-sm-ghost" id="ic-discover">Atualizar contas</button><button class="btn-sm-prim" id="ic-reimport">Reimportar tudo</button></div></div><div class="ic-grid">${INTEGRATORS.map(card).join('')}</div><div class="ic-account-section"><div class="ic-toolbar"><div><div class="section-title">Contas de anúncios conectadas</div><div class="ic-sub">Vincule cada conta Meta Ads ou Google Ads ao cliente correto.</div></div></div><div id="ic-accounts"></div></div>`;host.prepend(box);box.querySelector('#ic-discover').onclick=discoverAccounts;box.querySelector('#ic-reimport').onclick=reimportAll;box.querySelectorAll('[data-connect]').forEach(b=>b.onclick=()=>connect(b.dataset.connect));box.querySelectorAll('[data-sync]').forEach(b=>b.onclick=()=>b.dataset.sync==='organic'?syncOrganic():syncPaid(b.dataset.sync));renderAccounts();setTimeout(removeLegacyDirectBlocks,100);setTimeout(removeLegacyDirectBlocks,500);}
  function patchNav(){if(typeof nav!=='function'||nav.__integrationCenterV3)return false;const old=nav;nav=async function(page){const r=await old(page);if(page==='accounts')setTimeout(renderIntegrationCenter,30);return r};nav.__integrationCenterV3=true;return true}
  window.renderIntegrationCenter=renderIntegrationCenter;window.reimportAllIntegrations=reimportAll;wait(()=>patchNav());
})();
