import {createClient} from 'npm:@supabase/supabase-js@2.76.1';
const base=Deno.env.get('SUPABASE_URL')!;
const service=createClient(base,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const origin='https://mediahub.engajeperformance.com.br';
const callback=base+'/functions/v1/meta-auth/callback';
const cors={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,GET,OPTIONS'};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{...cors,'Content-Type':'application/json'}});
const graphVersion=Deno.env.get('META_GRAPH_VERSION')||'v26.0';
const metaId=Deno.env.get('META_APP_ID'),metaSecret=Deno.env.get('META_APP_SECRET');
type Integration={id:string;organization_id:string;provider:string;external_account_id:string;config:Record<string,unknown>;status:string;account_name:string};
async function check<T>(result:{data:T;error:unknown}):Promise<T>{if(result.error)throw new Error('Falha ao gravar no Supabase.');return result.data;}
async function hmac(text:string){if(!metaSecret)throw new Error('Configure META_APP_SECRET.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(metaSecret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(text)))).map(n=>n.toString(16).padStart(2,'0')).join('');}
async function graph(path:string,token:string,params:Record<string,string>={}){const url=new URL('https://graph.facebook.com/'+graphVersion+'/'+path);for(const [k,v]of Object.entries(params))url.searchParams.set(k,v);const r=await fetch(url,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(25000)});const body=await r.json();if(!r.ok||body.error)throw new Error('Meta recusou a consulta (código '+String(body.error?.code||r.status)+'). Confira permissões e validade da conexão.');return body;}
async function pages(path:string,token:string,params:Record<string,string>={}){const result:Record<string,any>[]=[];let after:string|undefined;for(let page=0;page<50;page++){const r=await graph(path,token,{...params,limit:'100',...(after?{after}:{})});result.push(...(r.data||[]));if(!r.paging?.next)return result;after=r.paging.cursors?.after;if(!after)throw new Error('A paginação da Meta não pôde ser concluída.');}throw new Error('Volume excede a sincronização interativa; reduza o período.');}
async function allowed(req:Request,org:string){const auth=req.headers.get('Authorization');if(!auth)throw new Error('Sessão necessária.');const client=createClient(base,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const {data:{user}}=await client.auth.getUser();if(!user)throw new Error('Sessão expirada.');const {data:superAdmin}=await client.rpc('is_super_admin');if(!superAdmin){const {data:member}=await service.from('organization_members').select('role,is_active,organizations!inner(status)').eq('organization_id',org).eq('user_id',user.id).single();if(!member?.is_active||!['client_admin','editor'].includes(member.role)||(member.organizations as any)?.status!=='active')throw new Error('Sem permissão para gerenciar integrações.');}return user;}
async function setToken(id:string,token:string){await check(await service.rpc('store_integration_token',{p_id:id,p_token:token}));}
function actionValue(actions:any[]|undefined,...keys:string[]):number|null{if(!actions)return null;for(const key of keys){const item=actions.find(a=>a.action_type===key);if(item)return Number(item.value);}return 0;}
async function sync(i:Integration){const token=await check(await service.rpc('integration_token',{p_id:i.id}));if(!token)throw new Error('Conta sem autorização. Reconecte.');let rows=0,creativeCount=0;
 if(i.provider==='meta_ads'){
  const data=await pages(i.external_account_id+'/insights',token,{level:'ad',date_preset:'last_30d',time_increment:'1',action_attribution_windows:'["7d_click"]',fields:'account_id,account_currency,campaign_id,campaign_name,adset_id,ad_id,date_start,spend,impressions,clicks,actions,action_values'});
  const facts=data.map(d=>({organization_id:i.organization_id,integration_id:i.id,platform:'meta_ads',metric_date:d.date_start,currency:d.account_currency,account_id:String(d.account_id),campaign_id:String(d.campaign_id),campaign_name:d.campaign_name,adset_id:d.adset_id,ad_id:String(d.ad_id),spend:Number(d.spend),revenue:actionValue(d.action_values,'omni_purchase','purchase','offsite_conversion.fb_pixel_purchase'),impressions:d.impressions==null?null:Number(d.impressions),clicks:d.clicks==null?null:Number(d.clicks),page_views:actionValue(d.actions,'landing_page_view'),leads:actionValue(d.actions,'lead','offsite_conversion.fb_pixel_lead'),checkouts:actionValue(d.actions,'initiate_checkout','offsite_conversion.fb_pixel_initiate_checkout'),purchases:actionValue(d.actions,'omni_purchase','purchase','offsite_conversion.fb_pixel_purchase'),attribution_window:'7d_click',synced_at:new Date().toISOString()}));
  for(let n=0;n<facts.length;n+=200){await check(await service.from('metrics_ads').upsert(facts.slice(n,n+200),{onConflict:'organization_id,platform,account_id,campaign_id,ad_id,metric_date,currency'}));rows+=facts.slice(n,n+200).length;}
  const ads=await pages(i.external_account_id+'/ads',token,{fields:'id,name,created_time,campaign_id,creative{id,thumbnail_url,image_url,body,video_id}'});
  for(const a of ads){if(!a.creative)continue;await check(await service.from('creatives').upsert({organization_id:i.organization_id,integration_id:i.id,platform:'meta_ads',account_id:i.external_account_id,external_id:a.id,ad_id:a.id,campaign_id:a.campaign_id,kind:a.creative.video_id?'video':'image',caption:a.creative.body||a.name,thumbnail_url:a.creative.thumbnail_url,media_url:a.creative.image_url,published_at:a.created_time,synced_at:new Date().toISOString()},{onConflict:'organization_id,platform,account_id,external_id'}));creativeCount++;}
 }else if(i.provider==='instagram_organic'||i.provider==='facebook_organic'){
  const ig=i.provider==='instagram_organic';const posts=await pages(i.external_account_id+(ig?'/media':'/published_posts'),token,{fields:ig?'id,caption,media_type,media_url,thumbnail_url,permalink,timestamp,like_count,comments_count':'id,message,full_picture,permalink_url,created_time,shares,reactions.limit(0).summary(true),comments.limit(0).summary(true)',...(ig?{}:{since:String(Math.floor(Date.now()/1000)-86400*30)})});
  for(const p of posts){await check(await service.from('creatives').upsert({organization_id:i.organization_id,integration_id:i.id,platform:i.provider,account_id:i.external_account_id,external_id:p.id,kind:p.media_type==='VIDEO'?'video':p.media_type==='CAROUSEL_ALBUM'?'carousel':'image',caption:p.caption||p.message||null,lifetime_metrics:ig?{likes:p.like_count??null,comments:p.comments_count??null}:{reactions:p.reactions?.summary?.total_count??null,comments:p.comments?.summary?.total_count??null,shares:p.shares?.count??null},thumbnail_url:p.thumbnail_url||p.full_picture||p.media_url||null,media_url:p.media_url||p.full_picture||null,permalink:p.permalink||p.permalink_url,published_at:p.timestamp||p.created_time,synced_at:new Date().toISOString()},{onConflict:'organization_id,platform,account_id,external_id'}));creativeCount++;}
 }else throw new Error('Este provedor ainda precisa do adaptador e das credenciais de API.');
 await check(await service.from('integrations').update({status:'connected',is_enabled:true,last_synced_at:new Date().toISOString(),last_error:null}).eq('id',i.id));
 return {message:`Sincronização concluída: ${rows} métricas e ${creativeCount} criativos gravados.${i.provider!=='meta_ads'?' Contadores acumulados estão nos posts; métricas diárias não foram importadas.':''}`,rows,creatives:creativeCount};
}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response(null,{headers:cors});const url=new URL(req.url);let activeId:string|undefined;
 try{
  if(req.method==='GET'&&url.pathname.endsWith('/callback')){
   const state=url.searchParams.get('state')||'';const [id,expiry,nonce,signature]=state.split('.');const signed=[id,expiry,nonce].join('.');if(!signature||signature!==await hmac(signed)||Number(expiry)<Date.now())throw new Error('Autorização expirada.');
   const {data:pending,error}=await service.from('integrations').update({status:'syncing'}).eq('id',id).eq('status','pending').select('*').single();if(error||!pending||pending.config.nonce!==nonce)throw new Error('Autorização já utilizada.');
   activeId=id;const actorId=pending.config.user_id;if(!actorId)throw new Error('Reconecte para renovar a autorização.');const {data:members}=await service.from('organization_members').select('organization_id,role,is_active,organizations!inner(status,is_agency)').eq('user_id',actorId).eq('is_active',true);const authorized=members?.some((m:any)=>m.organizations.status==='active'&&((m.organizations.is_agency&&m.role==='super_admin')||(m.organization_id===pending.organization_id&&['client_admin','editor'].includes(m.role))));if(!authorized)throw new Error('Permissão revogada durante a autorização.');const {data:org}=await service.from('organizations').select('slug,status').eq('id',pending.organization_id).single();if(!org||org.status!=='active')throw new Error('Cliente indisponível.');
   if(url.searchParams.get('error'))throw new Error('Autorização recusada.');const code=url.searchParams.get('code');if(!code)throw new Error('Código ausente.');
   const result=await graph('oauth/access_token','',{client_id:metaId!,client_secret:metaSecret!,redirect_uri:callback,code});let token=result.access_token;if(!token)throw new Error('Token não recebido.');
   const long=await graph('oauth/access_token','',{grant_type:'fb_exchange_token',client_id:metaId!,client_secret:metaSecret!,fb_exchange_token:token});token=long.access_token||token;
   const ads=pending.provider==='meta_ads';const accounts=await pages(ads?'me/adaccounts':'me/accounts',token,{fields:ads?'id,name,currency':'id,name,access_token,instagram_business_account{id,username}'});
   let imported=0;for(const a of accounts){const ig=pending.provider==='instagram_organic';if(ig&&!a.instagram_business_account)continue;const accountId=ig?a.instagram_business_account.id:a.id;const name=ig?a.instagram_business_account.username:a.name;const saved=await check(await service.from('integrations').upsert({organization_id:pending.organization_id,provider:pending.provider,external_account_id:accountId,account_name:name,status:'connected',is_enabled:false,config:{currency:a.currency||null},last_error:null},{onConflict:'organization_id,provider,external_account_id'}).select('id').single());await setToken(saved.id,ads?token:a.access_token||token);imported++;}
   await check(await service.from('integrations').delete().eq('id',id));
   return Response.redirect(origin+'/'+org.slug+'/settings/integrations?connected='+imported,303);
  }
  if(req.method!=='POST')return json({message:'Método inválido.'},405);
  const body=await req.json();const org=String(body.organizationId||'');if(!/^[0-9a-f-]{36}$/.test(org))throw new Error('Cliente inválido.');const actor=await allowed(req,org);
  if(body.action==='connect'){
   if(!['meta_ads','facebook_organic','instagram_organic'].includes(body.provider))return json({message:body.provider==='google_ads'?'Google Ads: adaptador ainda não implementado nesta versão.':body.provider==='tiktok_ads'?'TikTok Ads: requer aplicativo aprovado, TIKTOK_APP_ID e TIKTOK_APP_SECRET.':'Windsor: seleção de contas e adaptador Google ainda não habilitados nesta versão.'});
   if(!metaId||!metaSecret)return json({message:'Configure META_APP_ID e META_APP_SECRET no Supabase.'});
   const nonce=crypto.randomUUID();const pending=await check(await service.from('integrations').insert({organization_id:org,provider:body.provider,external_account_id:'pending:'+nonce,account_name:'Autorização em andamento',status:'pending',config:{nonce,user_id:actor.id}}).select('id').single());
   const signed=[pending.id,Date.now()+600000,nonce].join('.');const state=signed+'.'+await hmac(signed);const scopes=body.provider==='meta_ads'?'ads_read':body.provider==='facebook_organic'?'pages_show_list,pages_read_engagement':'pages_show_list,pages_read_engagement,instagram_basic';
   const login=new URL('https://www.facebook.com/'+graphVersion+'/dialog/oauth');login.search=new URLSearchParams({client_id:metaId,redirect_uri:callback,state,scope:scopes,response_type:'code'}).toString();return json({url:login.href});
  }
  if(body.action==='sync'){
   const {data:i}=await service.from('integrations').select('*').eq('id',body.integrationId).eq('organization_id',org).single();if(!i)throw new Error('Conta não encontrada.');activeId=i.id;
   const {data:locked}=await service.from('integrations').update({status:'syncing',last_sync_started_at:new Date().toISOString(),last_error:null}).eq('id',i.id).neq('status','syncing').select('id').maybeSingle();if(!locked)return json({message:'Esta conta já está sincronizando. Aguarde a conclusão.'});return json(await sync(i));
  }
  return json({message:'Ação inválida.'},400);
 }catch(e){const message=e instanceof Error?e.message:'Erro de sincronização';if(activeId)await service.from('integrations').update({status:'error',last_error:message.slice(0,300)}).eq('id',activeId);return json({message},400);}
});
