'use client';

import {useState} from 'react';
import {ArrowDown, ArrowUp, Filter, GripVertical, Plus, Trash2} from 'lucide-react';
import {funnelMetricDefinitions, funnelMetricGroups, funnelPresets, type FunnelMetricKey, type FunnelModel, type FunnelStepConfig} from '@/lib/metrics/funnel-config';
import {useSortableList} from '@/hooks/use-sortable-list';

export function FunnelConfigurator({initialModel,initialSteps}:{initialModel:FunnelModel;initialSteps:FunnelStepConfig[]}){
  const [model,setModel]=useState<FunnelModel>(initialModel);
  const [steps,setSteps]=useState<FunnelStepConfig[]>(initialSteps);
  const unused=funnelMetricDefinitions.filter((definition)=>!steps.some((step)=>step.metric===definition.key));
  const applyModel=(next:FunnelModel)=>{setModel(next);const preset=funnelPresets.find((item)=>item.id===next);if(preset&&next!=='custom')setSteps(preset.steps.map((step)=>({...step})));};
  const moveStep=(from:number,to:number)=>{if(from===to||from<0||to<0)return;setModel('custom');setSteps((current)=>{const next=[...current];const [item]=next.splice(from,1);next.splice(to,0,item);return next;});};
  const reorder=(active:FunnelMetricKey,target:FunnelMetricKey)=>{setModel('custom');setSteps((current)=>{const from=current.findIndex((item)=>item.metric===active);const to=current.findIndex((item)=>item.metric===target);if(from===to||from<0||to<0)return current;const next=[...current];const [item]=next.splice(from,1);next.splice(to,0,item);return next;});};
  const {dragging,over,selected,start,selectOrMove}=useSortableList<FunnelMetricKey>({selector:'[data-funnel-step]',attribute:'data-funnel-step',onMove:reorder});
  return <section className="space-y-5">
    <input type="hidden" name="funnel_model" value={model}/>
    <input type="hidden" name="funnel_steps" value={JSON.stringify(steps)}/>
    <div><h2 className="flex items-center gap-2 text-lg font-semibold"><Filter className="text-primary" size={18}/>Modelo do funil</h2><p className="muted mt-2 text-sm">O modelo define a jornada. As etapas continuam editáveis e usam somente dados recebidos das plataformas.</p></div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{funnelPresets.map((preset)=><button type="button" key={preset.id} onClick={()=>applyModel(preset.id)} className={`rounded-2xl border p-4 text-left transition ${model===preset.id?'border-primary/50 bg-primary/[.08] shadow-[inset_0_0_0_1px_rgb(var(--primary-rgb)/.12)]':'border-white/10 bg-black/10 hover:-translate-y-0.5 hover:border-white/20'}`}><strong className="text-sm">{preset.label}</strong><span className="mt-2 block text-xs leading-5 text-zinc-500">{preset.description}</span><span className="mt-3 block text-[10px] font-semibold uppercase tracking-[.12em] text-primary/80">{preset.steps.length} etapas</span></button>)}</div>
    <div className="rounded-2xl border border-white/10 bg-black/10 p-4 sm:p-5">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Etapas visíveis</h3><p className="muted mt-1 text-xs">Arraste qualquer área livre da etapa até a posição desejada ou clique na origem e depois no destino. Mínimo de 2 e máximo de 12 etapas.</p></div>{unused.length&&steps.length<12?<select className="min-w-72" aria-label="Adicionar etapa" value="" onChange={(event)=>{const metric=event.target.value as FunnelMetricKey;if(!metric)return;const definition=funnelMetricDefinitions.find((item)=>item.key===metric);if(definition){setModel('custom');setSteps((current)=>[...current,{metric,label:definition.label}]);}}}><option value="">+ Adicionar etapa</option>{funnelMetricGroups.map((group)=>{const options=unused.filter((item)=>item.group===group.id);return options.length?<optgroup label={group.label} key={group.id}>{options.map((item)=><option key={item.key} value={item.key}>{item.label}</option>)}</optgroup>:null;})}</select>:null}</div>
      <div className="space-y-2">{steps.map((step,index)=>{const definition=funnelMetricDefinitions.find((item)=>item.key===step.metric);const available=definition&&'dataKey' in definition;return <div className={`grid touch-none select-none gap-3 rounded-xl border p-3 transition sm:grid-cols-[auto_32px_1fr_auto] sm:items-center ${dragging===step.metric||selected===step.metric?'scale-[.99] border-primary/70 bg-primary/[.12] shadow-lg':over===step.metric?'border-emerald-400/70 bg-emerald-400/[.08]':'cursor-grab border-white/[.08] bg-white/[.025] active:cursor-grabbing'}`} key={step.metric} data-funnel-step={step.metric} onClick={(event)=>selectOrMove(step.metric,event)} onPointerDown={(event)=>start(step.metric,event)}><button type="button" aria-pressed={selected===step.metric} aria-label={`Selecionar ou arrastar ${step.label}`} title="Arraste ou clique para selecionar" className="cursor-grab touch-none rounded-lg border border-white/10 p-2 text-zinc-400 active:cursor-grabbing active:text-primary" onClick={(event)=>selectOrMove(step.metric,event,true)} onPointerDown={(event)=>{event.stopPropagation();start(step.metric,event,true);}}><GripVertical size={17}/></button><span className="grid size-8 place-items-center rounded-full bg-primary/10 text-xs font-bold text-primary">{index+1}</span><label className="text-xs text-zinc-500">Nome da etapa<input className="mt-1 w-full select-text" maxLength={40} value={step.label} onChange={(event)=>{setModel('custom');setSteps((current)=>current.map((item,itemIndex)=>itemIndex===index?{...item,label:event.target.value}:item));}}/><small className="mt-1 block">Métrica: {definition?.label} · Custo: {definition?.costLabel} · <span className={available?'text-emerald-400':'text-amber-300'}>{available?'Disponível nas integrações atuais':'Será preenchida quando a origem enviar o dado'}</span></small></label><div className="flex gap-1"><button type="button" aria-label={`Subir ${step.label}`} disabled={!index} className="rounded-lg border border-white/10 p-2 disabled:opacity-30" onClick={()=>moveStep(index,index-1)}><ArrowUp size={15}/></button><button type="button" aria-label={`Descer ${step.label}`} disabled={index===steps.length-1} className="rounded-lg border border-white/10 p-2 disabled:opacity-30" onClick={()=>moveStep(index,index+1)}><ArrowDown size={15}/></button><button type="button" aria-label={`Remover ${step.label}`} disabled={steps.length<=2} className="rounded-lg border border-red-500/20 p-2 text-red-300 disabled:opacity-30" onClick={()=>{setModel('custom');setSteps((current)=>current.filter((_,itemIndex)=>itemIndex!==index));}}><Trash2 size={15}/></button></div></div>;})}</div>
      {!unused.length||steps.length>=12?null:<p className="mt-4 flex items-center gap-2 text-xs text-zinc-600"><Plus size={13}/>As opções são agrupadas por fase da jornada. Etapas sem dados aparecem como “—”, nunca como zero inventado.</p>}
    </div>
  </section>;
}
