import Image from 'next/image';
import Link from 'next/link';
import {Images} from 'lucide-react';
import {Card} from '@/components/ui/card';
import {SortableCardGrid} from '@/components/dashboard/sortable-card-grid';
import {platformDashboards} from '@/lib/metrics/platforms';
import type {Row} from '@/types/database.types';

const labels:Record<string,string>={likes:'Curtidas',comments:'Comentários',shares:'Compartilhamentos',reactions:'Reações',reach:'Alcance',impressions:'Impressões',views:'Visualizações'};

export function CreativeLibrary({creatives,mode,storageKey,organicInsightsUnavailable,showAllHref}:{creatives:Row<'creatives'>[];mode:'paid'|'organic';storageKey:string;organicInsightsUnavailable:boolean;showAllHref?:string}){
  const identity=(creative:Row<'creatives'>)=>{const metrics=creative.lifetime_metrics&&typeof creative.lifetime_metrics==='object'&&!Array.isArray(creative.lifetime_metrics)?creative.lifetime_metrics as Record<string,unknown>:{};const source=metrics.video_id||metrics.image_hash||(creative.media_url||creative.thumbnail_url)?.split('?')[0]||metrics.creative_id||creative.ad_id||creative.external_id;const copy=`${creative.name||''}:${creative.description||creative.caption||''}`;return `${creative.platform}:${String(source)}:${copy}`;};
  const uniqueCreatives=[...new Map(creatives.map((creative)=>[mode==='paid'?identity(creative):creative.id,creative])).values()];
  const items=uniqueCreatives.map((creative)=>{const visual=mode==='paid'?(creative.media_url||creative.thumbnail_url):(creative.thumbnail_url||creative.media_url);return {id:creative.id,content:<article className={`group overflow-hidden rounded-xl border border-white/10 bg-black/10 transition ${mode==='paid'?'':'hover:-translate-y-0.5 hover:border-primary/30'}`}>
    {visual?(mode==='paid'&&creative.kind==='video'&&creative.media_url?<video className="aspect-square w-full bg-black object-contain" controls preload="metadata" poster={creative.thumbnail_url??undefined} src={creative.media_url}/>:<Image unoptimized={mode==='paid'} className={`aspect-square w-full object-contain ${mode==='paid'?'':'transition duration-300 group-hover:scale-[1.01]'}`} width={1080} height={1080} sizes="(max-width: 640px) 100vw, (max-width: 1280px) 50vw, (max-width: 1536px) 33vw, 25vw" src={visual} alt={(creative.name||creative.caption)?.slice(0,100)||'Criativo publicado'}/>):<div className="grid aspect-square place-items-center bg-white/5"><Images className="text-zinc-600"/></div>}
    <div className="p-4"><p className="text-xs font-medium text-primary">{platformDashboards.find((item)=>item.platform===creative.platform)?.label??creative.platform} · {creative.kind}</p>{mode==='paid'?<><h3 className="mt-2 line-clamp-2 font-semibold leading-6">{creative.name||`Anúncio ${creative.ad_id??creative.external_id}`}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-zinc-400">{creative.description||creative.caption||'Anúncio sem descrição cadastrada na plataforma.'}</p></>:<p className="mt-2 line-clamp-3 text-sm leading-6">{creative.caption||creative.description||'Publicação sem legenda'}</p>}
      {mode==='organic'?organicInsightsUnavailable?<p className="mt-4 rounded-lg border border-amber-400/20 bg-amber-400/[.06] p-3 text-xs leading-5 text-amber-200">Métricas indisponíveis. Reconecte a Meta com a permissão de Insights.</p>:<div className="mt-4 border-t border-white/10 pt-3 text-xs"><p className="mb-2 text-zinc-500">Acumulado até a sincronização</p>{Object.entries(creative.lifetime_metrics||{}).filter(([,value])=>typeof value==='number').map(([key,value])=><p key={key} className="flex justify-between py-1"><span>{labels[key]||key}</span><strong>{typeof value==='number'?value.toLocaleString('pt-BR'):'—'}</strong></p>)}<p className="mt-2 text-zinc-600">{new Date(creative.synced_at).toLocaleDateString('pt-BR')}</p></div>:null}
      {creative.permalink?<a target="_blank" rel="noopener noreferrer" className="mt-3 block text-xs text-zinc-400 hover:text-primary" href={creative.permalink}>Abrir publicação ↗</a>:null}
    </div>
  </article>}});
  const gridClassName="grid gap-5 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4";
  return <Card><div className="mb-5"><p className="eyebrow">{mode==='paid'?'Biblioteca de anúncios':'Biblioteca de posts'}</p><h2 className="mt-2 text-lg font-semibold">{mode==='paid'?'Criativos de mídia paga':'Posts publicados'}</h2><p className="muted mt-2 text-xs">{mode==='paid'?'Somente anúncios pagos, sem duplicidade, com mídia original, nome e descrição cadastrados na plataforma.':'Somente publicações orgânicas. Use os filtros para separar Facebook, Instagram e outros canais. Arraste qualquer card para reorganizar.'}</p></div>{items.length?(mode==='paid'?<div className={gridClassName}>{items.map((item)=><div className="h-full [&>*]:h-full" key={item.id}>{item.content}</div>)}</div>:<SortableCardGrid items={items} storageKey={storageKey} className={gridClassName}/>):<p className="muted py-10 text-center">Nenhum {mode==='paid'?'criativo de anúncio':'post orgânico'} encontrado.</p>}{showAllHref?<div className="mt-6 text-center"><Link className="inline-flex min-h-11 items-center justify-center rounded-xl border border-primary/25 bg-primary/[.07] px-5 text-sm font-semibold text-primary transition hover:bg-primary/[.12]" href={showAllHref}>Carregar todos os posts</Link></div>:null}</Card>;
}
