create table if not exists public.integration_accounts (
  id uuid primary key default gen_random_uuid(),
  provider_id text not null default 'windsor',
  connector text not null,
  external_account_id text not null,
  account_name text,
  client_id uuid references public.clients(id) on delete set null,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  last_discovered_at timestamptz default now(),
  last_sync_at timestamptz,
  last_error text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(provider_id, connector, external_account_id)
);

create table if not exists public.paid_media_metrics (
  id bigint generated by default as identity primary key,
  row_key text not null unique,
  platform text not null,
  provider_id text not null default 'windsor',
  connector text not null,
  client_id uuid references public.clients(id) on delete cascade,
  account_id text not null,
  account_name text,
  metric_date date not null,
  campaign_id text,
  campaign_name text,
  adset_id text,
  adset_name text,
  ad_id text,
  ad_name text,
  impressions bigint not null default 0,
  reach bigint not null default 0,
  clicks bigint not null default 0,
  spend numeric not null default 0,
  cpm numeric not null default 0,
  cpc numeric not null default 0,
  ctr numeric not null default 0,
  frequency numeric not null default 0,
  conversions numeric not null default 0,
  conversion_value numeric not null default 0,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create index if not exists idx_integration_accounts_client_connector on public.integration_accounts(client_id, connector);
create index if not exists idx_paid_media_metrics_client_platform_date on public.paid_media_metrics(client_id, platform, metric_date desc);
create index if not exists idx_paid_media_metrics_account_date on public.paid_media_metrics(account_id, metric_date desc);

alter table public.integration_accounts enable row level security;
alter table public.paid_media_metrics enable row level security;

drop policy if exists integration_accounts_read on public.integration_accounts;
create policy integration_accounts_read on public.integration_accounts for select to authenticated using (
  exists(select 1 from public.user_profiles p where p.id=auth.uid() and p.is_active and (p.role='super_admin' or p.client_id=integration_accounts.client_id))
  or exists(select 1 from public.user_profiles p where p.id=auth.uid() and p.is_active and p.role='super_admin')
);

drop policy if exists integration_accounts_admin_write on public.integration_accounts;
create policy integration_accounts_admin_write on public.integration_accounts for all to authenticated using (
  exists(select 1 from public.user_profiles p where p.id=auth.uid() and p.is_active and p.role='super_admin')
) with check (
  exists(select 1 from public.user_profiles p where p.id=auth.uid() and p.is_active and p.role='super_admin')
);

drop policy if exists paid_media_metrics_read on public.paid_media_metrics;
create policy paid_media_metrics_read on public.paid_media_metrics for select to authenticated using (
  exists(select 1 from public.user_profiles p where p.id=auth.uid() and p.is_active and (p.role='super_admin' or p.client_id=paid_media_metrics.client_id))
);

insert into public.integration_providers(id,name,provider_type,status,capabilities,is_active,updated_at)
values
('meta_ads','Meta Ads','aggregator','available','{"platforms":["meta_ads"],"domains":["paid"],"engine":"windsor","connector":"facebook"}'::jsonb,true,now()),
('google_ads','Google Ads','aggregator','available','{"platforms":["google_ads"],"domains":["paid"],"engine":"windsor","connector":"google_ads"}'::jsonb,true,now())
on conflict(id) do update set name=excluded.name,provider_type=excluded.provider_type,status=excluded.status,capabilities=excluded.capabilities,is_active=true,updated_at=now();

update public.integration_providers set is_active=false,updated_at=now() where id in ('meta_direct','google_direct','tiktok_direct','linkedin_direct','microsoft_direct','stract');
